#!/bin/bash
: ${URL_TO_WATCH:="http://dev.jhrb.us:8080"}
: ${URL_STARTED:="#othertools"} #Who needs to know the successful start?
: ${URL_FAILED:="@wizardofmath"} #Who needs to know when it fails?
if [ -z $SLACK_WEBHOOK_TOKEN ]; then
        echo "Need a webhook token..." 2>&1
        exit 0
fi

message(){
    local MESSAGE=${2}
    local SLACK_FROM=$(whoami)
    local SLACK_TO=${1}
    curl -s -X POST https://hooks.slack.com/services/${SLACK_WEBHOOK_TOKEN} -d "{ \"text\": \"${MESSAGE}\" , \"channel\": \"${SLACK_TO}\" , \"username\" : \"${SLACK_FROM}-Bot\" }"
}
message ${URL_STARTED} "I'll let you know when ${URL_TO_WATCH} is up"
COUNTER=0
while [[ "$(curl -s --max-time 1 ${URL_TO_WATCH}/ping)" != "pong" ]]
do
    [[ $COUNTER -gt 7200 ]] && break
    let COUNTER=COUNTER+1
done
if [[ "$(curl -s --max-time 1 ${URL_TO_WATCH}/ping)" == "pong" ]];then
    message ${URL_STARTED} "Server is running URL: ${URL_TO_WATCH} watched for ${COUNTER} tries"
else
    message ${URL_FAILED} "Server is not running ${URL_TO_WATCH}"
fi
