#!/bin/bash

xcode-select --install
touch ~/.profile # If you don't have it
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew tap caskroom/homebrew-cask
brew install brew-cask
brew cask install virtualbox
brew install coreutils
brew install maven
brew install liquibase
brew install gnu-sed --with-default-names
brew install boot2docker
brew install mysql
boot2docker init
boot2docker up
$(boot2docker shellinit)
# Now make docker go in all new shells
docker run busybox # Prove it works!
mysql.server start
echo "Run mysql -uroot # if you want to test that mysql is running."
sudo easy_install pip
sudo pip install tox # This gets your virtualenv too

# This will add stuff to .profile to ensure things work later.
echo "export LIQUIBASE_HOME=$(find /usr/local/Cellar/liquibase -name libexec)" >> ~/.profile
echo '$(boot2docker shellinit)' >> ~/.profile 