#!/bin/bash

function ll(){
    git log --all --graph --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
}
commits=$(ll)
echo $commits
x=$(echo $commits | grep \- | grep -i $1 | wc -l)
y=$(echo $commits | grep \- | grep -iv $1 | wc -l)
echo $1 wrote ${x} commits in this repo.
echo $1 did not write ${y} commits in this repo.
