#!/bin/bash

set -ex

echo . /source/scripts/.profile >> ~/.profile
echo . /source/scripts/.profile >> ~/.bashrc
echo . /source/scripts/.profile >> /etc/bash.bashrc
cd /source/scripts
mkdir /source/scripts/bin
apt-get update
apt-get install -y --no-install-recommends git curl vim openssh-client openssh-server ruby
curl --insecure -L http://stedolan.github.io/jq/download/linux64/jq -o /usr/bin/jq
chmod 755 /usr/bin/jq
sudo curl -k https://hub.github.com/standalone -Lo /usr/bin/hub
sudo chmod 755 /usr/bin/hub
